defaults:
  - pdb/base_transform_args@interdomain_distillation
  - _self_

interdomain_distillation:
  dataset:
    _target_: atomworks.ml.datasets.StructuralDatasetWrapper

    cif_parser_args:
      cache_dir: null
      load_from_cache: False
      save_to_cache: False
    
    dataset_parser:
      _target_: atomworks.ml.datasets.parsers.GenericDFParser
      pn_unit_iid_colnames:
        - pn_unit_1_iid
        - pn_unit_2_iid
      path_colname: path

    dataset:
      _target_: atomworks.ml.datasets.PandasDataset
      name: af2db_interdomain_distillation
      data: /projects/ml/datahub/dfs/af2db_interdomain_dset.parquet
      id_column: example_id
      columns_to_load:
        - example_id
        - path
        - pn_unit_1_iid
        - pn_unit_2_iid
        - cluster
    
    transform:
      crop_contiguous_probability: 0.0
      crop_spatial_probability: 1.0

  weights:
    _target_: atomworks.ml.samplers.calculate_weights_by_inverse_cluster_size
    cluster_column: cluster
  
