
defaults:
  - pdb/base_transform_args@bcov_ppi_distillation
  - _self_

bcov_ppi_distillation:
  dataset:
    _target_: atomworks.ml.datasets.datasets.StructuralDatasetWrapper

    cif_parser_args:
      cache_dir: null
      load_from_cache: False
      save_to_cache: False
    
    dataset_parser:
      _target_: atomworks.ml.datasets.parsers.GenericDFParser
      pn_unit_iid_colnames:
        - pn_unit_1_iid
        - pn_unit_2_iid
      path_colname: path

    dataset:
      _target_: atomworks.ml.datasets.datasets.PandasDataset
      name: bcov_ppi_distillation
      data: /projects/ml/datahub/dfs/bcov_ppi_dset_af3_preds.parquet
      id_column: example_id
      columns_to_load:
        - example_id
        - path
        - pn_unit_1_iid
        - pn_unit_2_iid
    
    transform:
      crop_contiguous_probability: 0.0
      crop_spatial_probability: 1.0



