name: modelhub
channels:
  - nvidia/label/cuda-12.6.0
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.12
  - cuda
  - pytorch=2.7
  - openbabel=3.1.1
  - pip:
    - -r file:requirements.txt 