
defaults:
  - design_base_interface_only
  - val/indexed@val.unconditional
  - _self_

global_transform_args:
  allowed_types: ['is_protein', 'is_ligand']
  sigma_perturb: 1.0

  # mask_args:
  #   # These first few args don't matter in this case
  #   low_prop: 0.2
  #   high_prop: 1.0
  #   broken_prop: 0.5
  #   mask_params:
  #     get_unconditional_diffusion_mask: {}
  #     get_ppi_mask: {}
  #   diff_mask_probs:
  #     get_unconditional_diffusion_mask: 0.10
  #     get_ppi_mask: 0.90

train:
  pdb:
    probability: 1.0
    sub_datasets:
      interface:
        dataset:
          dataset:
            filters:
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # interface specific filters
              - "~(pn_unit_1_non_polymer_res_names.notnull() and pn_unit_1_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              - "~(pn_unit_2_non_polymer_res_names.notnull() and pn_unit_2_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              - "is_inter_molecule"
              # ppi specific filters
              - "pn_unit_1_type.astype('str').str.match('${chain_type_info_to_regex:PROTEINS}')"
              - "pn_unit_2_type.astype('str').str.match('${chain_type_info_to_regex:PROTEINS}')"
            columns_to_load:
              # columns common across all PDB datasets
              - example_id
              - pdb_id
              - assembly_id
              - deposition_date
              - resolution
              - num_polymer_pn_units
              - method
              - cluster
              - n_prot
              - n_nuc
              - n_ligand
              - n_peptide
              # interface specific columns
              - pn_unit_1_iid
              - pn_unit_2_iid
              - pn_unit_1_non_polymer_res_names
              - pn_unit_2_non_polymer_res_names
              - is_inter_molecule
              - all_pn_unit_iids_after_processing
              - involves_loi
              # necessary if filtering by pn_unit_type
              - pn_unit_1_type
              - pn_unit_2_type
          transform:
            crop_contiguous_probability: 0.0
            crop_spatial_probability: 1.0
# val:
# TODO: INCLUDE A PPI VAL SET
  # ligand_conditioned:
  #     probability: 1.0

  # unconditional: 
  #   probability: 0.0

