
defaults:
  - indexed_conditioned
  # - val/unindexed@val.unindexed
  - _self_

crop_size: 200

global_transform_args:
  train_masks:
    unconditional:
      frequency: 0.
    indexed:
      frequency: 0.
    unindexed:
      frequency: 0.7


