defaults:
  - base

experiment:
  name: rf2aa-af3_v4
  trainer: "flow_matching"

training_params: 
  resume_from_checkpoint_path: /home/dimaio/RF2-allatom-af3/rf2aa/models/rf2aa-af3_v4_last.pt
  reset_optimizer_params: True
  EMA: 0.99
  weight_decay: 0.01
  learning_rate: .001
  learning_rate_schedule:
    num_warmup_steps: 0
    num_steps_decay: 5000
    decay_rate: 0.95
  grad_clip: 0.2
  use_amp: False
  ddp_backend: nccl

loader_params:
  maxseq: 1024
  maxtoken: 1024
  maxlat: 1

ddp_params:
  accum: 1
  batch_size: 1
  port: 12465

loss_param:
  w_dist: 1.0
  w_str: 0.0
  w_inter_fape: 0.0
  w_lig_fape: 0.0
  w_lddt: 0.0
  w_aa: 0.5
  w_bond: 0.0
  w_bind: 0.0
  binder_loss_label_smoothing: 0.0
  w_clash: 0.0
  w_atom_bond: 0.0
  w_skip_bond: 0.0
  w_rigid: 0.0
  w_hb: 0.0
  w_pae: 0.00
  w_pde: 0.00
  lj_lin: 0.75
  w_trans: 1.0
  t_normalize_clip: 0.925
  trans_scale: 1.0

interpolant:
  min_t: 1e-2
  separate_t: False
  provide_kappa: False
  hierarchical_t: False
  codesign_separate_t: False
  codesign_forward_fold_prop: 0.0
  codesign_inverse_fold_prop: 0.0

  twisting:
    use: False

  rots:
    corrupt: True
    train_schedule: linear
    sample_schedule: linear
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    train_schedule: linear
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  aatypes:
    corrupt: False
    schedule: linear
    schedule_exp_rate: 10
    temp: 1.0
    noise: 0.0
    do_purity: False
    train_extra_mask: 0.0
    interpolant_type: masking
    num_tokens: 80

  sampling:
    num_timesteps: 10
    do_sde: False
  self_condition: False

dataset_params:
  n_train: 25600
  validate_every_n_epochs: 1
  fraction_pdb: 0.12
  fraction_fb: 0.36
  fraction_compl: 0.055
  fraction_neg_compl: 0
  fraction_na_compl: 0.055
  fraction_neg_na_compl: 0
  fraction_distil_tf: 0.055
  fraction_tf: 0
  fraction_neg_tf: 0
  fraction_rna: 0.02
  fraction_dna: 0.005
  fraction_sm_compl: 0.11
  fraction_metal_compl: 0.03
  fraction_sm_compl_multi: 0.025
  fraction_sm_compl_covale: 0.025
  fraction_sm: 0.0
  fraction_atomize_pdb: 0.0425
  fraction_atomize_complex: 0.0425
  fraction_sm_compl_asmb: 0.055
  n_valid_pdb: 256
  n_valid_homo: 0
  n_valid_dslf: 0
  n_valid_compl: 256
  n_valid_neg_compl: 0
  n_valid_na_compl: 256
  n_valid_neg_na_compl: 0
  n_valid_distil_tf: 0
  n_valid_tf: 0
  n_valid_neg_tf: 0
  n_valid_rna: 256
  n_valid_dna: 256
  n_valid_sm_compl: 256
  n_valid_metal_compl: 0
  n_valid_sm_compl_multi: 0
  n_valid_sm_compl_covale: 0
  n_valid_sm_compl_strict: 256
  n_valid_sm: 0
  n_valid_atomize_pdb: 0
  n_valid_atomize_complex: 0
  n_valid_sm_compl_asmb: 0
  p_homo_cut: 0
  p_short_crop: 0
  p_dslf_crop: 0
  dslf_fb_upsample: 1

model:
  global_params:
    d_msa: 384
    d_msa_full: 64
    d_pair: 128
    d_state: 128

  embedding:
    rf2aa:
      params:
        p_drop: 0.15
        d_templ: 64
        n_head_templ: 4
        d_hidden_templ: 64
        templ_p_drop: 0.25
        symmetrize_repeats: False
        repeat_length: null
        symmsub_k: null
        sym_method: null
        main_block: null
        copy_main_block_template: False
        additional_dt1d: 0
        recycling_type: "msa_pair_only"
        use_same_chain: False
  blocks:
    AF3_full:
      num_blocks: 4
      params:
        p_drop_row: 0.25
        p_drop_pair: 0.25
        msa_transition_drop: 0.0
        outer_product_channels: 16
        p_drop_outer_product: 0.0
        n_pair_head: 6
        n_pair_channels: 32
        n_msa_head: 8
        n_msa_channels: 8
        norm_msa_row: False
    AF3:
      num_blocks: 48
      params:
        p_drop_row: 0.25
        p_drop_pair: 0.25
        msa_transition_drop: 0.0
        outer_product_channels: 16
        p_drop_outer_product: 0.0
        n_pair_head: 6
        n_pair_channels: 32
        n_msa_head: 8
        n_msa_channels: 32
        norm_msa_row: False
  refinement:
    generative:
      params:
        num_attention_layers: 24
        num_channels: 32
        num_degrees: 2
        num_layers: 3
        n_heads: 4
        div: 4
        l0_in_features: 128
        l0_out_features: 128
        num_edge_features: 32
        n_channels: 32
        msa_transition_drop: 0.0
        compute_gradients: True
  auxiliary_predictors:
    c6d:
      n_feat: 128
      input_feature: "pair"
    mlm:
      n_feat: 384
      input_feature: "msa"