# Status: unvetted

defaults:
  - af3_repro_single_example_small
  - _self_

af3_data_prep:
  D: 12

lightning:
  trainer:
    accumulate_grad_batches: 1

inference:
  checkpoint: /net/scratch/ahern/af3-repro-debug/tmp_checkpoints/working_4_test_2/saved/epoch=1-step=800.ckpt
  