defaults:
  - af3_repro_single_example
  - _self_

model:
  recycler:
    n_pairformer_blocks: 10

recycling:
  max_cycle: 1

loader_params:
  maxcycle: 1
  #   template_embedder:
  #     n_block: 2
  #   msa_module:
  #     n_block: 2
  # diffusion_module:
  #   atom_attention_encoder:
  #     atom_transformer:
  #       diffusion_transformer:
  #         n_block: 2
  #   diffusion_transformer:
  #     n_block: 2
  #   atom_attention_decoder:
  #     atom_transformer:
  #       diffusion_transformer:
  #         n_block: 2
