defaults:
  - af3_repro_single_example_small
  - _self_
  - dataset_params/dataset_params_no_distillation

cpu_training: true
training_params:
  ddp_backend: gloo

model:
  recycler:
    n_pairformer_blocks: 1
    template_embedder:
      n_block: 1
    msa_module:
      n_block: 1
  diffusion_module:
    atom_attention_encoder:
      atom_transformer:
        diffusion_transformer:
          n_block: 1
    diffusion_transformer:
      n_block: 1
    atom_attention_decoder:
      atom_transformer:
        diffusion_transformer:
          n_block: 1

logger:
  sublogger:
    save_dir: af3-debug-cpu

autograd_detect_anomaly: true