defaults:
  # - af3
  - rf2aa
  - _self_

experiment:
  name: rf2aa-af3-repro
  trainer: af3_repro
  output_dir: null

loss:
  diffusion_loss:
    _target_: rf2aa.loss.af3_losses.DiffusionLoss
    weight: 4.0
    sigma_data: ${model.diffusion_module.sigma_data}
    alpha_dna: 5
    alpha_rna: 5
    alpha_ligand: 10
    edm_lambda: True
    se3_invariant_loss: True
    clamp_diffusion_loss: False
  distogram_loss:
    _target_: rf2aa.loss.af3_losses.DistogramLoss
    weight: 3e-2
  protein_ligand_bond_loss:
    _target_: rf2aa.loss.af3_losses.ProteinLigandBondLoss
    weight: 0
  #confidence_loss:
    #weight: 1e-4
    #plddt:
      #weight: 1.0
      #n_bins: 50
      #max_value: 1.0
    #pae:
      #weight: 1.0
      #n_bins: 64
      #max_value: 32
    #pde:  
      #weight: 1.0
      #n_bins: 64
      #max_value: 32
    #exp_resolved:
      #weight: 1.0
      #n_bins: 2
      #max_value: 1

metrics:
  interface_lddt:
    _target_: rf2aa.metrics.lddt_metrics.InterfaceLDDT
  chain_lddt:
    _target_: rf2aa.metrics.lddt_metrics.ChainLDDT
  example_id:
    _target_: rf2aa.metrics.metrics_base.AddExampleID
  distogram:
    _target_: rf2aa.metrics.distogram_metrics.DistogramLoss

ddp_params:
  batch_size: 1
  accum: 3

loader_params:
  p_msa_mask: 0.0
  maxseq: 5132
  n_fallback_retries: 10
  maxcycle: 4
  maxcycle_valid: 10
  dataloader_kwargs:
    shuffle: False
    num_workers: 3
    #prefetch_factor: 4
    pin_memory: True

training_params: 
  learning_rate_schedule:
    num_warmup_steps: 1000
    num_steps_decay: 50000
    decay_rate: 0.95
  grad_clip: 10.0
  EMA: 0.999
  seed: 1

interpolant:
  sigma_data: 16

  min_t: 1e-2
  separate_t: False
  provide_kappa: False
  hierarchical_t: False
  codesign_separate_t: False
  codesign_forward_fold_prop: 0.0
  codesign_inverse_fold_prop: 0.0

  twisting:
    use: False

  rots:
    corrupt: True
    train_schedule: linear
    sample_schedule: linear
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    train_schedule: linear
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  aatypes:
    corrupt: False
    schedule: linear
    schedule_exp_rate: 10
    temp: 1.0
    noise: 0.0
    do_purity: False
    train_extra_mask: 0.0
    interpolant_type: masking
    num_tokens: 80

  sampling:
    num_timesteps: 20
    do_sde: False
  self_condition: False

model_globals:
  l_max: 40000  # shouldn't matter...
model:
  c_s: 384
  c_z: 128
  c_atom: 128
  c_atompair: 16
  c_s_inputs: 449
  feature_initializer:
    c_s_inputs: ${model.c_s_inputs}
    input_feature_embedder:
      features:
        - restype
        - profile
        - deletion_mean
      atom_attention_encoder:
        c_token: 384
        c_atom_1d_features: 389
        c_tokenpair: ${model.c_z}
        atom_1d_features:
          - ref_pos
          - ref_charge
          - ref_mask
          - ref_element
          - ref_atom_name_chars
        atom_transformer:
          n_queries: 32
          n_keys: 128
          l_max: ${model_globals.l_max}
          diffusion_transformer:
            n_block: 3
            diffusion_transformer_block:
              n_head: 4
    relative_position_encoding:
      r_max: 32
      s_max: 2
  recycler:
    n_pairformer_blocks: 48
    pairformer_block:
      p_drop: 0.25
      triangle_multiplication:
        d_hidden: 128
      triangle_attention:
        n_head: 4
        d_hidden: 32
      attention_pair_bias:
        n_head: 16
    template_embedder:
      n_block: 2
      raw_template_dim: 108
      c: 64
    msa_module:
      n_block: 4
      c_m: 64
      p_drop_msa: 0.15
      p_drop_pair: 0.25
      msa_subsample_embedder:
        num_sequences: 1024
        dim_raw_msa: 34
        c_s_inputs: ${model.c_s_inputs}
        c_msa_embed: ${model.recycler.msa_module.c_m}
      outer_product: 
        c_msa_embed: ${model.recycler.msa_module.c_m}
        c_outer_product: 32
        c_out: ${model.c_z}
      msa_pair_weighted_averaging: 
        n_heads: 8
        c_weighted_average: 32
        c_msa_embed: ${model.recycler.msa_module.c_m}
        c_z: ${model.c_z}
      msa_transition: 
        n: 4  
        c: ${model.recycler.msa_module.c_m}
      triangle_multiplication_outgoing: 
        d_pair: ${model.c_z}
        d_hidden: 128
        bias: True
      triangle_multiplication_incoming: 
        d_pair: ${model.c_z}
        d_hidden: 128
        bias: True
      triangle_attention_starting: 
        d_pair: ${model.c_z}
        n_head: 4
        d_hidden: 32
        p_drop: 0.0
      triangle_attention_ending: 
        d_pair: ${model.c_z}
        n_head: 4
        d_hidden: 32
        p_drop: 0.0
      pair_transition: 
        n: 4
        c: ${model.c_z}

  diffusion_module:
    sigma_data: ${interpolant.sigma_data}
    c_token: 768
    f_pred: edm
    diffusion_conditioning:
      c_s_inputs: ${model.c_s_inputs}
      c_t_embed: 256
      relative_position_encoding:
        r_max: 32
        s_max: 2
    atom_attention_encoder:
      c_tokenpair: ${model.c_z}
      c_atom_1d_features: 389
      atom_1d_features:
          - ref_pos
          - ref_charge
          - ref_mask
          - ref_element
          - ref_atom_name_chars
      atom_transformer:
        n_queries: 32
        n_keys: 128
        l_max: ${model_globals.l_max}
        diffusion_transformer:
          n_block: 3
          diffusion_transformer_block:
            n_head: 4
    diffusion_transformer:
      n_block: 24
      diffusion_transformer_block:
        n_head: 16
    atom_attention_decoder:
      atom_transformer:
        n_queries: 32
        n_keys: 128
        l_max: ${model_globals.l_max}
        diffusion_transformer:
          n_block: 3
          diffusion_transformer_block:
            n_head: 4
  distogram_head:
    bins: 65 
confidence_head:
  c_s: ${model.c_s}
  c_z: ${model.c_z}
  n_pairformer_layers: 4
  pairformer:
    p_drop: 0.25
    c: 128
    attention_pair_bias:
      n_head: 16 
  n_bins_pae: 64
  n_bins_pde: 64
  n_bins_plddt: 50
  n_bins_exp_resolved: 2

optimizer:
  type: Adam
  params:
    lr: 1.8e-3
    betas: [0.9, 0.95]
    eps: 1.0e-8

logger:
  save_dir: csv_logs
  use_wandb: False
  sublogger:
    project: af3-debug

callbacks:
  log_metrics: {}

af3_data_prep:
  D: 32
  sigma_data: ${model.diffusion_module.sigma_data}
  s_trans: 1
  random_augmentation: True
  only_ca: False
  t: null

af3_inference:
  second_order_solver: False

resume:
  False

paths:
  pdb_data_dir: /projects/ml/datahub/dfs/af3_splits/2024_12_16
  protein_msa_dirs:
    - {"dir": "/projects/msa/rf2aa_af3/rf2aa_paper_model_protein_msas", "extension": ".a3m.gz", "directory_depth": 2}
    - {"dir": "/projects/msa/rf2aa_af3/missing_msas_through_2024_08_12", "extension": ".msa0.a3m.gz", "directory_depth": 2}
  rna_msa_dirs:
    - {"dir": "/projects/msa/rf2aa_af3/rf2aa_paper_model_rna_msas", "extension": ".afa", "directory_depth": 0}
  
cif_parser_caching_args:
  #cache_dir: /projects/ml/RF2_allatom/cache/cif
  cache_dir: /net/tukwila/RF2_allatom/cache/cif
  load_from_cache: False
  save_to_cache: False


dataset_params:
  constructor:
    _target_: "rf2aa.data.compose_data_datahub_new.NewDatapipeTrainer"
  diffusion_batch_size: 32
  diffusion_batch_size_valid: ${dataset_params.diffusion_batch_size}

  n_msa: 1024
  default_transform: datahub.pipelines.af3.build_af3_transform_pipeline
  train:
    # ... train datasets
    pdb:
      probability: 0.5
      sub_datasets:
        pn_unit:
          dataset: 
            _target_: datahub.datasets.datasets.StructuralDatasetWrapper
            save_failed_examples_to_dir: null
            cif_parser_args: ${cif_parser_caching_args}
            dataset_parser:
              _target_: datahub.datasets.parsers.PNUnitsDFParser
            dataset:
              _target_: datahub.datasets.datasets.PandasDataset
              name: pn_unit
              id_column: example_id
              data: ${paths.pdb_data_dir}/pn_units_df_train.parquet
              filters:
                - "deposition_date < '2021-09-30'"
                - "resolution < 9.0"
                - "num_polymer_pn_units <= 300"
                - "cluster.notnull()"
                - "~(q_pn_unit_non_polymer_res_names.notnull() and q_pn_unit_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants.AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              columns_to_load:
                # columns required for identification, filtering & weighting
                - example_id
                - pdb_id
                - assembly_id
                - deposition_date
                - resolution
                - num_polymer_pn_units
                - method
                - cluster
                - n_prot
                - n_nuc
                - n_ligand
                # pn_unit specific columns
                - q_pn_unit_iid
                - q_pn_unit_non_polymer_res_names
                - all_pn_unit_iids_after_processing
                - q_pn_unit_is_loi
            return_key: null
            transform:
              _target_: ${dataset_params.default_transform}
              is_inference: False
              protein_msa_dirs: ${paths.protein_msa_dirs}
              rna_msa_dirs: ${paths.rna_msa_dirs}
              n_recycles: ${loader_params.maxcycle}
              crop_size: ${loader_params.crop}
              crop_contiguous_probability: 0.3333333333333333
              crop_spatial_probability: 0.6666666666666667
              diffusion_batch_size: ${dataset_params.diffusion_batch_size}
              max_atoms_in_crop: 5000
              n_msa: ${dataset_params.n_msa}
          weights:
            _target_: datahub.samplers.calculate_weights_for_pdb_dataset_df
            beta: 0.5
            alphas:
              a_prot: 3.0
              a_nuc: 3.0
              a_ligand: 1.0
              a_loi: 5.0

        interface:
          dataset:
            _target_: datahub.datasets.datasets.StructuralDatasetWrapper
            save_failed_examples_to_dir: null
            cif_parser_args: ${cif_parser_caching_args}
            dataset_parser:
              _target_: datahub.datasets.parsers.InterfacesDFParser
            dataset:
              _target_: datahub.datasets.datasets.PandasDataset
              name: interface
              id_column: example_id
              data: ${paths.pdb_data_dir}/interfaces_df_train.parquet
              filters:
                - "deposition_date < '2021-09-30'"
                - "resolution < 9.0"
                - "num_polymer_pn_units <= 300"
                - "cluster.notnull()"
                - "~(pn_unit_1_non_polymer_res_names.notnull() and pn_unit_1_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants.AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
                - "~(pn_unit_2_non_polymer_res_names.notnull() and pn_unit_2_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants.AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
                - "is_inter_molecule"
              columns_to_load:
                # columns required for identification, filtering & weighting
                - example_id
                - pdb_id
                - assembly_id
                - deposition_date
                - resolution
                - num_polymer_pn_units
                - method
                - cluster
                - n_prot
                - n_nuc
                - n_ligand
                # interface specific columns
                - pn_unit_1_iid
                - pn_unit_2_iid
                - pn_unit_1_non_polymer_res_names
                - pn_unit_2_non_polymer_res_names
                - is_inter_molecule
                - all_pn_unit_iids_after_processing
                - involves_loi
            return_key: null
            transform:
              _target_: ${dataset_params.default_transform}
              is_inference: False
              protein_msa_dirs: ${paths.protein_msa_dirs}
              rna_msa_dirs: ${paths.rna_msa_dirs}
              n_recycles: ${loader_params.maxcycle}
              crop_size: ${loader_params.crop}
              crop_contiguous_probability: 0.0
              crop_spatial_probability: 1.0
              diffusion_batch_size: ${dataset_params.diffusion_batch_size}
              max_atoms_in_crop: 5000
              n_msa: ${dataset_params.n_msa}
          weights:
            _target_: datahub.samplers.calculate_weights_for_pdb_dataset_df
            beta: 0.5
            alphas:
              a_prot: 3.0
              a_nuc: 3.0
              a_ligand: 1.0
              a_loi: 5.0

    monomer_distillation:
      probability: 0.5
      sub_datasets:
        af2fb_distillation:
          dataset:
            _target_: datahub.datasets.datasets.StructuralDatasetWrapper
            save_failed_examples_to_dir: null

            # cif parser
            cif_parser_args:
              #assume_residues_all_resolved: true
              cache_dir: null
              load_from_cache: false
              save_to_cache: false 

            # metadata parser
            dataset_parser:
              _target_: datahub.datasets.parsers.AF2FB_DistillationParser

            # metadata dataset
            dataset:
              _target_: datahub.datasets.datasets.PandasDataset
              name: af2fb_distillation
              id_column: example_id
              data: /squash/af2_distillation_facebook/af2_distillation_facebook.parquet
              columns_to_load:
                - example_id
                - sequence_hash
            return_key: null
            transform:
              _target_: ${dataset_params.default_transform}
              is_inference: False
              protein_msa_dirs: [{"dir": "/squash/af2_distillation_facebook/msa", "extension": ".a3m", "directory_depth": 2}]
              rna_msa_dirs: []
              n_recycles: ${loader_params.maxcycle}
              crop_size: ${loader_params.crop}
              crop_contiguous_probability: 0.25
              crop_spatial_probability: 0.75
              diffusion_batch_size: ${dataset_params.diffusion_batch_size}
              max_atoms_in_crop: 5000
              n_msa: ${dataset_params.n_msa}


  val:
    # ... val datasets
    interface:
      _target_: datahub.datasets.datasets.StructuralDatasetWrapper
      dataset_parser:
        _target_: datahub.datasets.parsers.ValidationDFParserLikeAF3
      dataset:
        _target_: datahub.datasets.datasets.PandasDataset
        name: val
        #id_column: ${dataset_params.train.interface.dataset.dataset.id_column}
        id_column: example_id
        data: ${paths.pdb_data_dir}/entry_level_val_df.parquet
        filters:
          - "example_id not in  [\"{['validation']}{7ptq}{1}{[]}\"]"
      return_key: null
      transform:
        _target_: ${dataset_params.default_transform}
        is_inference: True
        protein_msa_dirs: ${paths.protein_msa_dirs}
        rna_msa_dirs: ${paths.rna_msa_dirs}
        n_recycles: ${loader_params.maxcycle_valid}
        crop_size: ${loader_params.crop}
        crop_contiguous_probability: 0.0
        crop_spatial_probability: 0.0
        diffusion_batch_size: ${dataset_params.diffusion_batch_size_valid}
        n_msa: ${dataset_params.n_msa}
        
