defaults:
  - base 

experiment:
  name: rf2aa-reproduction
  trainer: "composed"

model: 
  global_params:
    d_msa: 256
    d_msa_full: 64
    d_pair: 192
    d_state: 64

  embedding:
    rf2aa:
      params: 
        p_drop: 0.15
        d_templ: 64
        n_head_templ: 4
        d_hidden_templ: 64
        templ_p_drop: 0.25
        symmetrize_repeats: False
        repeat_length: null
        symmsub_k: null
        sym_method: null
        main_block: null
        copy_main_block_template: False
        additional_dt1d: 0
        recycling_type: "msa_pair"
        use_same_chain: False
  blocks:
    untied_p2p_full:
      num_blocks: 4
      params:
        d_rbf: 64
        p_drop_row: 0.25
        p_drop_pair: 0.25
        p_drop_layer: 0.0
        msa_transition_drop: 0.0
        outer_product_channels: 16 
        p_drop_outer_product: 0.0
        n_pair_head: 6
        n_pair_channels: 32
        n_msa_head: 8
        n_msa_channels: 8
        structure_bias_gate_channels: 16
        structure_bias_channels: 64
        n_se3_layers: 1
        n_se3_channels: 32
        n_se3_degrees: 2
        n_se3_head: 4
        n_div: 4
        l0_in_features: 64
        l0_out_features: 64
        l1_in_features: 6
        l1_out_features: 2
        n_se3_edge_features: 64
        sc_pred_d_hidden: 128
        sc_pred_p_drop: 0.0
        residual_state: True
        norm_msa_row: False
        use_flash_attn: True
        compute_gradients: False
    untied_p2p:
      num_blocks: 32
      params:
        d_rbf: 64
        p_drop_row: 0.25
        p_drop_pair: 0.25
        p_drop_layer: 0.0
        msa_transition_drop: 0.0
        outer_product_channels: 16 
        p_drop_outer_product: 0.0
        n_pair_head: 6
        n_pair_channels: 32
        n_msa_head: 8
        n_msa_channels: 32
        structure_bias_gate_channels: 16
        structure_bias_channels: 64
        n_se3_layers: 1
        n_se3_channels: 32
        n_se3_degrees: 2
        n_se3_head: 4
        n_div: 4
        l0_in_features: 64
        l0_out_features: 64
        l1_in_features: 6
        l1_out_features: 2
        n_se3_edge_features: 64
        sc_pred_d_hidden: 128
        sc_pred_p_drop: 0.0
        residual_state: True
        norm_msa_row: False
        use_flash_attn: True
        compute_gradients: False
  refinement:
    local:
      params:
        num_iterations: 4
        d_rbf: 64
        n_se3_layers: 2
        n_se3_channels: 32
        n_se3_degrees: 2
        n_se3_head: 4
        n_div: 4
        l0_in_features: 64
        l0_out_features: 64
        l1_in_features: 6
        l1_out_features: 2
        n_se3_edge_features: 64
        top_k: 64
        sc_pred_d_hidden: 128
        sc_pred_p_drop: 0.15
        residual_state: True
        compute_gradients: False

  auxiliary_predictors:
    c6d:
      n_feat: 192
      input_feature: "pair"
    mlm:
      n_feat: 256
      input_feature: "msa"
    pae:
      n_feat: 192
      input_feature: "pair"
    plddt: 
      n_feat: 64
      input_feature: "state"

dataset_params:
  n_train: 24000
  validate_every_n_epochs: 1
  fraction_pdb: 0.3
  fraction_fb: 0.0
  fraction_compl: 0.1
  fraction_neg_compl: 0
  fraction_na_compl: 0.1
  fraction_neg_na_compl: 0
  fraction_distil_tf: 0.0
  fraction_tf: 0
  fraction_neg_tf: 0
  fraction_rna: 0.03
  fraction_dna: 0.02
  fraction_sm_compl: 0.15
  fraction_metal_compl: 0.04
  fraction_sm_compl_multi: 0.03
  fraction_sm_compl_covale: 0.03
  fraction_sm: 0.0
  fraction_atomize_pdb: 0.06
  fraction_atomize_complex: 0.06
  fraction_sm_compl_asmb: 0.08
  n_valid_pdb: 256
  n_valid_compl: 256
  n_valid_rna: 256
  n_valid_dna: 256
  n_valid_sm_compl: 256
  n_valid_sm_compl_strict: 256
training_params:
  EMA: 0.99
  weight_decay: 0.01
  learning_rate: .001
  learning_rate_schedule:
    num_warmup_steps: 0
    num_steps_decay: 5000
    decay_rate: 0.95
  grad_clip: 0.2
  use_amp: True

chem_params:
  use_lj_params_for_atoms: True
  use_phospate_frames_for_NA: False
