defaults:
  - design_callbacks
  - _self_

dump_validation_structures_callback:
  dump_every_n: 5
  extra_fields:
    - is_motif_atom_with_fixed_seq

run_pipelines_callback:
  _target_: rfd3.callbacks.RunPipelinesCallback
  save_dir: ${paths.output_dir}
  run_every_n_epochs: 5
  pipelines_config_path: ${paths.root_dir}/rfd3/configs/pipelines/aa_ppi_design_af3_validation.yaml
  pipelines_script_path: ${paths.root_dir}/lib/pipelines/pipelines/pipeline.py