# base training dataset for training AF3 design models (atom14 variants):
# protein subsampling only.

defaults:
  - design_base

  # Validation sets
  # - val/sm_binder_hbonds@val.sm_binder_hbonds
  # - val/unindexed@val.unindexed
  - val/mcsa_41_short_rigid@val.mcsa_41_short_rigid
  - val/bcov_ppi_easy_medium@val.bcov_ppi_easy_medium
  - val/unconditional@val.unconditional
  # - val/sm_binder_hbonds_short@val.sm_binder_hbonds_short
  # - val/unconditional_deep@val.unconditional_deep
  # - val/indexed@val.indexed

  # Training Sets
  - train/pdb/dna_binder@train.dna_binder
  - train/pdb/na_complex_distillation@train.na_complex_distillation
  - train/pdb/free_dna_dds@train.free_dna_dds
  - train/bcov_ppi_distillation@train

  - _self_

val:
  # Small datasets;
  unconditional:
    dataset:
      eval_every_n: 1

  # Medium:
  mcsa_41_short_rigid:
    dataset:
      eval_every_n: 1

train:
  # Additional datasets beyond the base training dataset
  dna_binder:
    probability: 0.0
  na_complex_distillation:
    probability: 0.0
  free_dna_dds:
    probability: 0.0
  bcov_ppi_distillation:
    probability: 0.0
  interdomain_distillation:
    probability: 0.0