# # base training dataset for training AF3 design models on the DNA binder task specifically:

defaults:
  - base
  - train/pdb/dna_binder@train.dna_binder
  - train/pdb/rfd3_train_pn_unit@train.rfd3_train_pn_unit
  - train/pdb/na_complex_distillation@train.na_complex_distillation
  - train/pdb/free_dna_dds@train.free_dna_dds

  - val/dna_binder_short@val.dna_binder

  - conditions/unconditional@global_transform_args.train_conditions.unconditional
  - _self_

pipeline_target: rfd3.transforms.pipelines.build_atom14_base_pipeline

global_transform_args:
  n_atoms_per_token: 14
  central_atom: CB
  sigma_perturb: 1.0
  sigma_perturb_com: 0.0
  association_scheme: atom14  # atom14, atom14-new or null
  center_option: "all" # options are ["all", "motif", "diffuse"]

  # Reference conformer policy
  generate_conformers: False
  generate_conformers_for_non_protein_only: False
  provide_reference_conformer_when_unmasked: False
  ground_truth_conformer_policy: IGNORE # Other options: REPLACE, ADD, FALLBACK. See atomworks.enums for details
  provide_elements_for_unindexed_components: False

  # PPI Cropping
  keep_full_binder_in_spatial_crop: False
  max_binder_length: 170

  # PPI Hotspots
  max_ppi_hotspots_frac_to_provide: 0.2
  ppi_hotspot_max_distance: 4.5

  # Secondary structure features
  max_ss_frac_to_provide: 0.4
  min_ss_island_len: 1
  max_ss_island_len: 10

  train_conditions:
    unconditional:
      frequency: 1.0
    sequence_design:
      frequency: 0.0
    island:
      frequency: 0.0
    tipatom:
      frequency: 0.0
    ppi:
      frequency: 0.0
    
  meta_conditioning_probabilities:
    calculate_rasa: 0.0
    keep_protein_motif_rasa: 0.0
    calculate_hbonds: 1.0
    hbond_subsample: 0.5

    # Conditioning token scheme probabilities
    unindex_leak_global_index: 0.0
    unindex_insert_random_break: 0.0
    unindex_remove_random_break: 0.0

    # Probability of adding 1d secondary structure conditioning
    add_1d_ss_features: 0.0

    # Probability of adding global secondary structure conditioning
    add_global_is_non_loopy_feature: 0.0

    # PPI
    add_ppi_hotspots: 0
    full_binder_crop: 0


# Base config overrides:
seed: 42
diffusion_batch_size_train: 32
diffusion_batch_size_inference: 8
crop_size: 256
n_recycles_train: 1
n_recycles_validation: 1
n_msa: null
max_atoms_in_crop: 2560  # 256x14 doesnt work since we pad up | 256 x 10

train:
  dna_binder:
    probability: 0.55
  rfd3_train_pn_unit:
    probability: 0.2
  na_complex_distillation:
    probability: 0.19
  free_dna_dds:
    probability: 0.06

