
defaults:
  - design_base
  - val/unindexed@val.unindexed
  - val/mcsa_41_short_rigid@val.mcsa_41_short_rigid
  - _self_

diffusion_batch_size_train: 24

global_transform_args:
  train_conditions:
    unconditional:
      frequency: 3.0
    sequence_design:
      frequency: 0.5
    island:
      frequency: 3.0
      p_unindex_motif_tokens: 0.5
    tipatom:
      frequency: 3.0
      p_unindex_motif_tokens: 0.5
