
defaults:
  - optimizers/adam@optimizer
  - schedulers/af3@lr_scheduler
  - components/ema@ema
  - _self_

lr_scheduler:
  base_lr: 1.8e-3
  warmup_steps: 500

ema:
  decay: 0.99

net:
  _target_: projects.aa_design.model.aa_design.AF3Design

  c_s_init: 416
  c_s: 384
  c_z: 128
  c_atom: 128
  c_atompair: 16

  inference_sampler:
    solver: "af3"
    num_timesteps: 200
    min_t: 0
    max_t: 1
    sigma_data: ${model.net.diffusion_module.sigma_data}
    s_min: 4e-4
    s_max: 160
    p: 7
    gamma_0: 0.8
    gamma_min: 1.0
    noise_scale: 1.003
    step_scale: 1.5

  token_initializer: # formerly known as the trunk
    relative_position_encoding:
      r_max: 32
      s_max: 2
    c_token_to_embed: 384

    n_pairformer_blocks: 2  # small pairformer to transfer information from Z_II to S_I
    pairformer_block:
      p_drop: 0.25
      triangle_multiplication:
        d_hidden: 128
      triangle_attention:
        n_head: 4
        d_hidden: 32
      attention_pair_bias:
        n_head: 16
      use_triangle_attn: False

  diffusion_module:
    _target_: ???
    c_token: 768
    sigma_data: 16
    f_pred: edm

    ########################################################################
    # Encoders
    ########################################################################
    diffusion_token_encoder:  
      c_t_embed: 256  # Time
      n_bins: 65
      sigma_data: ${model.net.diffusion_module.sigma_data}  # distogram scaling
      use_distogram: True

    diffusion_atom_encoder:
      c_atom_1d_features: 393
      atom_1d_features:
          - ref_pos
          - ref_charge
          - ref_mask
          - ref_element
          - ref_atom_name_chars
          - ref_is_motif_atom_mask
          - ref_motif_atom_type
      broadcast_trunk_feats_on_1dim_old: True
    
    ########################################################################
    # 
    ########################################################################
