
defaults:
  - base
  - _self_

net:
  diffusion_module:
    _target_: projects.aa_design.model.diffusion_modules.UNetDiffusionModule

    ########################################################################
    # U-Net architecture
    ########################################################################
    atom_attention_encoder:
      atom_transformer:
        diffusion_transformer:
          n_block: 3
          diffusion_transformer_block:
            n_head: 4
            no_residual_connection_between_attention_and_transition: True
            kq_norm: False
    
    diffusion_transformer:
      n_registers: 0
      n_block: 24
      diffusion_transformer_block:
        n_head: 16
        no_residual_connection_between_attention_and_transition: True
        kq_norm: True
    
    atom_attention_decoder:
      atom_transformer:
        n_queries: 32
        n_keys: 128
        diffusion_transformer:
          n_block: 3
          diffusion_transformer_block:
            n_head: 4
            no_residual_connection_between_attention_and_transition: True
            kq_norm: False
    
    ########################################################################
    # 
    ########################################################################

