# AF3 dataset configuration with monomer distillation

defaults:
  - base

  # Training
  - train/pdb/af3_train_interface@train.pdb.sub_datasets.interface
  - train/pdb/af3_train_pn_unit@train.pdb.sub_datasets.pn_unit

  # Validation
  # (Standard RFScore validation)
  - val/rfscore@val.unconditional
  - val/rfscore@val.ground_truth_conformers
  # (Experimental data validation)
  - val/af3_validation@val.ts1_unconditional
  - val/af3_validation@val.ts1_ground_truth_conformers

  - _self_

# Dataloading pipeline to use (custom)
pipeline_target: projects.rfscore.pipelines.rfscore.build_rfscore_transform_pipeline

# Dataset weighting
train: 
  # AF-3's PDB dataset
  pdb:
    probability: 1.0
    sub_datasets:
      interface:
        dataset:
          dataset:
            filters:                                                                                                                                                                                                                                                                                                                                         
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # interface specific filters
              # ... remove entries with excluded ligands (in either query pn_unit)
              - >
                ~(pn_unit_1_non_polymer_res_names.notnull() and
                pn_unit_1_non_polymer_res_names.str.contains(
                '${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}',
                regex=True))
              - >
                ~(pn_unit_2_non_polymer_res_names.notnull() and
                pn_unit_2_non_polymer_res_names.str.contains(
                '${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}',
                regex=True))
              - "is_inter_molecule"
              # ... filter to only protein-ligand interfaces
              - "(n_prot == 1 and n_nuc == 0 and n_ligand == 1)"
          transform:
            use_element_for_atom_names_of_atomized_tokens: True
      pn_unit:
        dataset:
          dataset:
            filters:                                                                                                                                                                                                                                                                                                                                         
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # pn_unit specific filters
              # ... remove entries where the query pn_unit includes excluded ligands
              - "~(q_pn_unit_non_polymer_res_names.notnull() and q_pn_unit_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              # only proteins or ligands
              - "(n_prot == 1 or n_ligand == 1)"
          transform:
            use_element_for_atom_names_of_atomized_tokens: True
val:
  # Standard validation
  unconditional:
    dataset:
      transform:
        p_use_ground_truth_conformer: 0.0 # Never use the ground truth conformer
        use_element_for_atom_names_of_atomized_tokens: True
  ground_truth_conformers:
    dataset:
      transform:
        p_use_ground_truth_conformer: 1.0 # Always use the ground truth conformer
        use_element_for_atom_names_of_atomized_tokens: True
  # Validation as a scoring function for experimental data
  # (without templating)
  ts1_unconditional:
    dataset:
      dataset_parser:
        _target_: datahub.datasets.parsers.GenericDFParser
        attrs:
          selection_strings:
            - "B/*/*/C5"
            - "A/*/128/CB"
            - "A/*/95/N"
            - "A/*/95/CD2"
            - "A/*/53/O"
      dataset:
        data: /projects/ml/rfscore/datasets/experimental_validation/serine_hydrolase/dfs/ts1.parquet
      transform:
        p_use_ground_truth_conformer: 0.0 # Never use the ground truth conformer
        use_element_for_atom_names_of_atomized_tokens: True
    key_to_balance: null # (Because we inherit from AF-3 validation, we must set to null)

  # (with templating)
  ts1_ground_truth_conformers:
    dataset:
      dataset_parser:
        _target_: datahub.datasets.parsers.GenericDFParser
        attrs:
          selection_strings:
            - "B/*/*/C5"
            - "A/*/128/CB"
            - "A/*/95/N"
            - "A/*/95/CD2"
            - "A/*/53/O"
      dataset:
        data: /projects/ml/rfscore/datasets/experimental_validation/serine_hydrolase/dfs/ts1.parquet
      transform:
        p_use_ground_truth_conformer: 1.0 # Never use the ground truth conformer
        use_element_for_atom_names_of_atomized_tokens: True
    key_to_balance: null # (Because we inherit from AF-3 validation, we must set to null)
  