# Standard AF-3 training with experimental data validation

defaults:
  - base

  # Training
  - train/pdb/af3_train_interface@train.pdb.sub_datasets.interface
  - train/pdb/af3_train_pn_unit@train.pdb.sub_datasets.pn_unit

  # Standard validation (conditional and unconditional)
  - val/rfscore@val.unconditional
  - val/rfscore@val.template_ligand
  - val/rfscore@val.template_polymer
  - val/rfscore@val.template_all

  - _self_

pipeline_target: projects.rfscore.pipelines.rfscore.build_rfscore_transform_pipeline

# TRAINING
# We train with the same dataset as AF-3, with the following modifications:
# - We use element types as atom names for atomized tokens
# - We add ground-truth templates conditioning, adding up to 1A noise to all tokens
train: 
  pdb:
    probability: 1.0
    sub_datasets:
      interface:
        dataset:
          transform:
            use_element_for_atom_names_of_atomized_tokens: False
            # +-- Conditioning --+
            # (Unconditional)
            p_unconditional: 0.9 # Show no conditioning, anywhere, X% of the time
            # (Templates)
            train_template_noise_scales:
              not_atomized: 0.1 # X angstrom of noise
              atomized: 0.1 # X angstrom of noise
            allowed_chain_types_for_conditioning: 
              _target_: cifutils.enums.ChainType.get_all_types
            p_condition_per_token: 0.1 # X% of the tokens have conditions
            p_provide_inter_molecule_distances: 0.0 # X% of the time, show inter-molecule distances
            # (Reference conformer)
            p_give_non_polymer_ref_conf: 0.5 # For X% of non-polymer residues, show the reference conformer (when sampling conditionally)
            p_give_polymer_ref_conf: 0.05  # For X% of polymer residues, show the reference conformer (when sampling conditionally)
            # (Skip MSA)
            p_skip_msa: 0.0 # X% of the time that we are sampling conditionally, skip the MSA
          dataset:
            filters:
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # interface specific filters
              - "~(pn_unit_1_non_polymer_res_names.notnull() and pn_unit_1_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              - "~(pn_unit_2_non_polymer_res_names.notnull() and pn_unit_2_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              - "is_inter_molecule"
              # only protein-ligand interfaces
              - "(n_prot == 1 and n_nuc == 0 and n_ligand == 1)"
      pn_unit:
        dataset:
          transform:
            use_element_for_atom_names_of_atomized_tokens: False
            # +-- Conditioning --+
            # (Unconditional)
            p_unconditional: 0.9 # Show no conditioning, anywhere, X% of the time
            # (Templates)
            train_template_noise_scales:
              not_atomized: 0.1 # X angstrom of noise
              atomized: 0.1 # # X angstrom of noise
            allowed_chain_types_for_conditioning: 
              _target_: cifutils.enums.ChainType.get_all_types
            p_condition_per_token: 0.1 # 10% of the tokens have conditions
            p_provide_inter_molecule_distances: 0.0 # X% of the time, show inter-molecule distances
            # (Reference conformer)
            p_give_non_polymer_ref_conf: 0.5 # For X% of non-polymer residues, show the reference conformer
            p_give_polymer_ref_conf: 0.05 # For X% of polymer residues, show the reference conformer
            # (Skip MSA)
            p_skip_msa: 0.0 # X% of the time that we are sampling conditionally, skip the MSA
          dataset:
            filters:                                                                                                                                                                                                                                                                                                                                         
              # (from before)
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              - "~(q_pn_unit_non_polymer_res_names.notnull() and q_pn_unit_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"

              # only proteins or ligands
              - "(n_prot == 1 or n_ligand == 1)"

# VALIDATION
val:
  ##### STANDARD VALIDATION #####
  # No conditioning information provided
  unconditional:
    dataset:
      transform:
        use_element_for_atom_names_of_atomized_tokens: False
        # +-- Conditioning --+
        p_unconditional: 1.0 # Never show conditioning
        p_skip_msa: 0.0 # Always show MSA

  # No noise on ligand atoms
  template_ligand:
    dataset:
      transform:
        use_element_for_atom_names_of_atomized_tokens: False
        # +-- Conditioning --+
        p_unconditional: 0.0 # Always show conditioning
        # (Templates)
        inference_template_noise_scales:
          not_atomized: null # Does not matter; no conditioning (not an allowed chain type)
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_non_polymers
        p_condition_per_token: 1.0
        p_provide_inter_molecule_distances: 0.0
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 1.0
        p_give_polymer_ref_conf: 0.0
        # (Skip MSA)
        p_skip_msa: 0.0 # Always show MSA

  # No noise on polymer atoms
  template_polymer:
    dataset:
      transform:
        use_element_for_atom_names_of_atomized_tokens: False
        # +-- Conditioning --+
        p_unconditional: 0.0 # Always show conditioning
        # (Templates)
        inference_template_noise_scales:
          not_atomized: 1e-4 # No noise on polymer atoms (epsilon to avoid division by zero)
          atomized: null # Does not matter; no conditioning
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_polymers
        p_condition_per_token: 1.0
        p_provide_inter_molecule_distances: 0.0
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 0.0
        p_give_polymer_ref_conf: 0.0
        # (Skip MSA)
        p_skip_msa: 0.0 # Always show MSA

  # Template all, including inter-chain distances (if using) and polymer reference conformers
  template_all:
    dataset:
      transform:
        use_element_for_atom_names_of_atomized_tokens: False
        # +-- Conditioning --+
        p_unconditional: 0.0 # Always show conditioning
        # (Templates)
        inference_template_noise_scales:
          not_atomized: 1e-4 # No noise on polymer atoms (epsilon to avoid division by zero)
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_all_types
        p_condition_per_token: 1.0
        p_provide_inter_molecule_distances: 0.0
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 1.0
        p_give_polymer_ref_conf: 1.0
        # (Skip MSA)
        p_skip_msa: 0.0 # Always show MSA
