# rfscore dataset configuration: 
# TRAINING: Only PDB protein-small molecule interfaces
# VALIDATION: Different noise scales for polymer and ligand atoms

defaults:
  - base
  - train/pdb/af3_train_interface@train.pdb.sub_datasets.interface
  - train/pdb/af3_train_pn_unit@train.pdb.sub_datasets.pn_unit
  - val/rfscore@val.unconditional
  - val/rfscore@val.noise_ligand_5A
  - val/rfscore@val.noise_ligand_0A
  - _self_

# Dataloading pipeline to use (custom)
pipeline_target: projects.rfscore.pipelines.rfscore.build_rfscore_transform_pipeline

# Dataset weighting
train: 
  # AF-3's PDB dataset
  pdb:
    probability: 1.0
    sub_datasets:
      interface:
        dataset:
          dataset:
            filters:                                                                                                                                                                                                                                                                                                                                         
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # interface specific filters
              # ... remove entries with excluded ligands (in either query pn_unit)
              - >
                ~(pn_unit_1_non_polymer_res_names.notnull() and
                pn_unit_1_non_polymer_res_names.str.contains(
                '${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}',
                regex=True))
              - >
                ~(pn_unit_2_non_polymer_res_names.notnull() and
                pn_unit_2_non_polymer_res_names.str.contains(
                '${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}',
                regex=True))
              - "is_inter_molecule"
              # ... filter to only protein-ligand interfaces
              - "(n_prot == 1 and n_nuc == 0 and n_ligand == 1)"
      pn_unit:
        dataset:
          dataset:
            filters:                                                                                                                                                                                                                                                                                                                                         
              # filters common across all PDB datasets
              - "deposition_date < '2021-09-30'"
              - "resolution < 9.0"
              - "num_polymer_pn_units <= 300" 
              - "cluster.notnull()"
              # pn_unit specific filters
              # ... remove entries where the query pn_unit includes excluded ligands
              - "~(q_pn_unit_non_polymer_res_names.notnull() and q_pn_unit_non_polymer_res_names.str.contains('${resolve_import:cifutils.constants,AF3_EXCLUDED_LIGANDS_REGEX}', regex=True))"
              # only proteins or ligands
              - "(n_prot == 1 or n_ligand == 1)"
val:
  # No conditioning information provided
  unconditional:
    dataset:
      transform:
        inference_template_noise_scales:
          not_atomized: 0.0 # Does not matter; no conditioning
          atomized: 0.0 # Does not matter; no conditioning
        allowed_chain_types_for_conditioning: null
  # 5A noise on ligand atoms
  noise_ligand_5A:
    dataset:
      transform:
        inference_template_noise_scales:
          not_atomized: 0.0 # Does not matter; no conditioning
          atomized: 5.0 # Moderate noise on ligand atoms
  # Negligible noise on ligand atoms
  noise_ligand_0A:
    dataset:
      transform:
        inference_template_noise_scales:
          not_atomized: 0.0 # Does not matter; no conditioning
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
