# @package _global_
defaults:
  - /inference_engine/af3
  - _self_

_target_: projects.rfscore.inference_engines.rfscore.RFScoreInferenceEngine

ckpt_path: /projects/ml/rfscore/inference/rfscore_no_confidence_2025-03-03.ckpt

template_selection_strings: null
