channels:
  - nvidia/label/cuda-12.4.0
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  # Dependencies above-and-beyond those in the base environment
  - pip:
    - xgboost>=2.1.4,<3
    - scikit-learn>=1.6.1,<2
