# Pipeline for online validation runs during PPI training of AF3-based design (atom14)
# Given a directory of predicted structures, will apply backbone filters, run MPNN, refold with AF-multimer, and compute metrics
# In the future, AF3 may be added as an option, but will be more compute-intensive

defaults:
  - pipeline

steps: [link_from_dir, get_ss_content, backbone_geometry_metrics, 
  filter_passing, mpnn, af_multimer_ppi, af_multimer_filter, update_benchmark]

# steps: [link_from_dir, get_ss_content, backbone_geometry_metrics, 
#   filter_passing, mpnn, af_multimer_ppi, af_multimer_filter]

af_multimer_ppi:
  chunk_by_delimiter: _
  chunk: 24

rundir: ??? # {training_log_dir}/pipelines/{epoch_number}/{dataset_name} # Will be specified in the call to subprocess

num_workers: 5

link_from_dir:
  raise_on_missing_trbs: False
  dir: ???

get_ss_content:
  exclude_motif: True

# TODO: Point to a version outside of my home directory once one exists for the refactor
paths:
  mpnn_repo: /home/rib7/protocols/fused_mpnn

backbone_geometry_metrics:
  assert_pass_rate_greater_than: -1 # We want metrics regardless
  exclude_motif: True

mpnn:
  enhanced: true
  model_type: ligand_mpnn
  num_seq_per_pdb: 3 # Bcov recommendation
  slurm:
    requeue_on_preempt: True
    max_resubmission_fraction: 1
    time: 01:00:00
    p: cpu
  chunk: 24

update_benchmark:
  benchmark_dir: ${rundir}/../../../val_metrics
  benchmark_name: aa_design_validation
  additional_columns:
    # These will be set programmatically in the callback
    model: null
    epoch: null
    dataset: null
    # ckpt: null
    user: ${oc.env:USER}
    rundir: ${rundir}