defaults:
  - aa_ppi_design_af3_validation

steps: [link_from_dir, get_ss_content, backbone_geometry_metrics, 
  filter_passing, mpnn, af3_ppi, af3_ppi_filter, update_benchmark]

# This config is primarily intended for offline validation with 10 replicates
af3_ppi:
  chunk: 72
  slurm:
    time: 02:00:00
    p: gpu # Because when I launch this after a promising training run, I get impatient... :)