# Pipeline for online validation runs during training of AF3-based design (atom14)
# Given a directory of predicted structures, will apply backbone filters, run MPNN, refold with AF2, and compute metrics
# In the future, AF3 may be added as an option, but will be more compute-intensive

defaults:
  - pipeline

# TODO: Tmalign doesn't work well with CIF -- switch to new diversity metric?

steps: [link_from_dir, get_ss_content, backbone_geometry_metrics, 
  filter_passing, mpnn, af2, calculate_designability, af2_filter, update_benchmark]

af2:
  slurm:
    p:
      gpu-bf
    gres: gpu:a4000:1
    requeue_on_preempt: True
    max_resubmission_fraction: 1
    time: 02:00:00
  chunk: 20

rundir: ??? # {training_log_dir}/pipelines/{epoch_number}/{dataset_name} # Will be specified in the call to subprocess

# TODO: Point to a version out of my home directory once one exists for the refactor!!
paths:
  mpnn_repo: /home/rib7/protocols/fused_mpnn

link_from_dir:
  dir: ??? # {training_log_dir}/val_structures/{epoch_number}/{dataset_name}

tmalign_diversity:
  command: /software/utils/TMalign
  write_to_cif: False

backbone_geometry_metrics:
  assert_pass_rate_greater_than: -1 # We want metrics regardless

mpnn:
  enhanced: true
  model_type: ligand_mpnn
  # TODO: Bump the below back up to 8! This is for debugging only
  num_seq_per_pdb: 1
  slurm:
    requeue_on_preempt: True
    max_resubmission_fraction: 1
    time: 01:00:00
    p: cpu-bf
  chunk: 8

update_benchmark:
  # If either of the two below are changed, the LogPipelinesResultsCallback would have to be modified accordingly
  benchmark_dir: ${rundir}/../../../val_metrics
  benchmark_name: aa_design_validation
  additional_columns:
    # These will be set programmatically in the callback
    model: null
    epoch: null
    dataset: null
    # ckpt: null
    user: ${oc.env:USER}
    rundir: ${rundir}

# TODO: Could add the af2 align rmsd metrics, and potentially even filter on these.
