
defaults:
  - pipeline

clear_rundir: False

steps: [link_from_dir, get_ss_content, tmalign_diversity, backbone_geometry_metrics, 
  filter_passing, mpnn, af2, calculate_designability, af2_filter, update_benchmark]

af3_design:
  dump_traj: True
  num_designs: 100
  chunk: 10
mpnn:
  chunk: 8
af2:
  chunk: 20
update_benchmark:
  _target_: pipelines.blocks.util_blocks.update_benchmark_block
  benchmark_name: unconditional
  benchmark_dir: /home/jbutch/software/stable/pipelines/benchmarks
  additional_columns:
    model: null  # will set as rundir basename
    epoch: 0
    ckpt: null
    user: ${oc.env:USER}
    rundir: ${rundir}
rf_diffusion:
  num_designs: 100
  chunk: 10
  command_args: >
    --config-name=aa_v2
    inference.input_pdb=/home/jbutch/Projects/MT24/rf_diffusion_repo/rf_diffusion/test_data/1qys.pdb
    diffuser.T=25
    contigmap.contigs=[\'100-100\']
    inference.idealize_sidechain_outputs=False
