defaults:
  - train_logging
  - dump_validation_structures
  - _self_

  
# Validation metrics:
store_validation_metrics_in_df_callback:
    _target_: modelhub.callbacks.metrics_logging.StoreValidationMetricsInDFCallback
    save_dir: ${paths.output_dir}/val_metrics

dump_validation_structures_callback:
  _target_: projects.aa_design.callbacks.DumpDesignStructuresValidationCallback
  dump_predictions: True
  one_model_per_file: False
  dump_trajectories: False
  dump_every_n: 5
  # dump_denoised_trajectories_only: True

# Other:
log_design_validation_metrics_callback:
  _target_: projects.aa_design.callbacks.LogDesignValidationMetricsCallback

log_learning_rate_callback:
  log_every_n: 25 # default 10

log_af3_training_losses_callback:
  log_full_batch_losses: False
  log_every_n: 25 # default 10