
_target_: projects.aa_design.transforms.masks.IndexedMask
frequency: 1.0

island_len_min: 1
island_len_max: 35
n_islands_min: 2
n_islands_max: 5
n_motif_tokens_max: null

p_mask_motif_sequence: 1.0   # probability that sequence is masked for motifs during training
p_mask_motif_sidechains: 0.8 # often mask sidechains


