
defaults:
  - indexed
  - _self_

_target_: projects.aa_design.transforms.masks.UnindexedMask

frequency: 1.0

# Use smaller masks for unindexed
island_len_min: 1
island_len_max: 5
n_islands_min: 2
n_islands_max: 5
n_motif_tokens_max: 15

p_mask_motif_sequence: 1.0
p_mask_motif_sidechains: 1.0

