# @package _global_

hydra:
  searchpath:
    - pkg://configs

defaults:
  - model: unet
  - trainer: aa_design
  - datasets: design_base
  - callbacks: design_callbacks
  - dataloader: fast
  - paths: default
  - hydra: default
  - logger: csv
  - _self_
  - experiment: ???
  - debug: null

# Placeholders from environment.yaml
name: ???
tags: ???
project: aa_design
# Names;
task_name: "validate"
seed: 42

callbacks:
  dump_validation_structures_callback:
    dump_predictions: True
    one_model_per_file: True
    dump_trajectories: True

# Args:
ckpt_path: ???
