defaults:
  - default

fit_and_evaluate_on_experimental_data_callback:
    _target_: projects.rfscore.callbacks.experimental_validation.FitAndEvaluateOnExperimentalDataCallback
    # Metric outputs to use as features for experimental validation
    feature_metrics:
      - selected_atom_by_atom_distances
    datasets:
      - ts1_unconditional