# AF3 dataset configuration with monomer distillation

defaults:
  - base
  # The @ symbol specifies the tree under which the item will be attached to the config
  - train/pdb/af3_train_interface@train.pdb.sub_datasets.interface
  - train/pdb/af3_train_pn_unit@train.pdb.sub_datasets.pn_unit
  - train:
    - monomer_distillation
    - na_complex_distillation
  - val/af3_validation@val.af3_validation
  - _self_

# Dataloading pipeline to use
pipeline_target: datahub.pipelines.af3.build_af3_transform_pipeline

# Dataset weighting
train: 
  pdb:
    probability: 0.50
  monomer_distillation:
    probability: 0.48
  na_complex_distillation:
    probability: 0.02