# AF3 dataset configuration with monomer distillation

defaults:
  - base
  # The @ symbol specifies the tree under which the item will be attached to the config
  - val/af3_validation@val.template_ligand
  - val/af3_validation@val.template_protein
  - val/af3_validation@val.template_none
  - _self_

# Dataloading pipeline to use
pipeline_target: modelhub.data.pipelines.build_af3_transform_pipeline

val:
  template_ligand:
    dataset:
      dataset:
        filters:
          # Only score examples with protein-ligand interfaces
          - "interfaces_to_score.str.contains('protein-ligand')"
          # Small examples only - very fast
          - "n_tokens_total < 400"
      transform:
        # +-- Conditioning --+
        p_unconditional: 0.0 # Always show conditioning
        # (Templates)
        template_noise_scales:
          not_atomized: 1e-4 # No noise on polymer atoms (epsilon to avoid division by zero)
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_non_polymers
        p_condition_per_token: 1.0 # Always condition
        p_provide_inter_molecule_distances: 0.0 # No inter-chain distances
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 1.0 # Always give non-polymer reference conformers
        p_give_polymer_ref_conf: 0.0 # Never give polymer reference conformers
  template_protein:
    dataset:
      dataset:
        filters:
          # Only score examples with protein-ligand interfaces
          - "interfaces_to_score.str.contains('protein-ligand')"
          # Small examples only - very fast
          - "n_tokens_total < 400"
      transform:
        # +-- Conditioning --+
        p_unconditional: 0.0 # Always show conditioning
        # (Templates)
        template_noise_scales:
          not_atomized: 1e-4 # No noise on polymer atoms (epsilon to avoid division by zero)
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_polymers
        p_condition_per_token: 1.0 # Always condition
        p_provide_inter_molecule_distances: 0.0 # No inter-chain distances
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 0.0 # Never give non-polymer reference conformers
        p_give_polymer_ref_conf: 1.0 # Always give polymer reference conformers
  template_none:
    dataset:
      dataset:
        filters:
          # Only score examples with protein-ligand interfaces
          - "interfaces_to_score.str.contains('protein-ligand')"
          # Small examples only - very fast
          - "n_tokens_total < 400"
      transform:
        # +-- Conditioning --+
        p_unconditional: 1.0 # Never show conditioning
        # (Templates)
        template_noise_scales:
          not_atomized: 1e-4 # No noise on polymer atoms (epsilon to avoid division by zero)
          atomized: 1e-4 # No noise on ligand atoms (epsilon to avoid division by zero)
        allowed_chain_types_for_conditioning:
          _target_: cifutils.enums.ChainType.get_polymers
        p_condition_per_token: 0.0 # Never condition
        p_provide_inter_molecule_distances: 0.0 # No inter-chain distances
        # (Reference conformer)
        p_give_non_polymer_ref_conf: 0.0 # Never give non-polymer reference conformers
        p_give_polymer_ref_conf: 0.0 # Never give polymer reference conformers